- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/WebConfig.java
BE/fix/cors_fix -> dev
정해진 경로에 대해서만 CORS가 동작하도록 수정하였습니다.
Close #88
> [BE] CORS 관련 최종 수정

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/WebConfig.java
BE/fix/cors_localhost
localhost 오타 수정
> [BE] fix: CORS localhost 오타 수정

- .github/ISSUE_TEMPLATE/⚒️-refactor.md
COMMON/docs/issue_refactor
리팩토링 관련 이슈 템플릿 추가
> [COMMON] refactor 이슈 템플릿 추가

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/CarDictController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/CarDict.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/CarDictDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/CarDictRepository.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/CarDictRepositoryImpl.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/CarDictService.java
BE/feat/car_dict -> dev
백카사전 엔드포인트를 구현했습니다.
Close #96
> feat: /car_dict 엔드포인트 구현

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/TagController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/CoreOption.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/DefaultCategory.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/DefaultOption.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/ExteriorColor.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/InteriorColor.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/PurchaseHistory.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/Tag.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/Trim.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/CoreOptionDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/DefaultOptionCategoryDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/DefaultOptionDetailDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/DefaultOptionDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/ExteriorColorDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/InteriorColorDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/TrimDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/PurchaseHistoryRepository.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/PurchaseHistoryRepositoryImpl.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/TagService.java
BE/feat/tag_userinfo_package -> dev
1. lombok을 적용하지 않았던 클래스들을 lombok을 사용하도록 수정하였습니다. 단, 기존 API와의 호환성을 위해 TrimDto는 제외되었습니다.(isBest가 아니라 best를 반환하고 있었음.)
2. purchase_history 테이블 정의 변경(purchase_tag_map 삭제, tag1_id, tag2_id, tag3_id 추가)에 따라 수정이 필요한 부분을 수정하였습니다.
3. /tag/option_package/{packageName} 엔드포인트를 구현하였습니다.(다만, 성능 이슈는 여전합니다.)
Close #109
> [BE] /tag/option_package/{packageName} 엔드포인트 구현

- backend/ohmycarset/build.gradle
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/OpenApiConfig.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/CarDictController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/CoreOptionController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/DefaultOptionController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/ExteriorColorController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/InteriorColorController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/SelectiveOptionController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/TagController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/TrimController.java
- backend/ohmycarset/src/main/resources/application.properties
BE/feat/swagger -> dev
swagger 문서화를 적용하였습니다.
/docs로 접근하면 사용 가능합니다.
Close #90
> [BE] swagger 문서 추가

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/OpenApiConfig.java
BE/fix/swagger_https -> dev
https에서 swagger의 failed to fetch 오류를 해결합니다.
Close #114
> [BE] https에서 swagger 오동작 해결

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/SelectiveOptionController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/TagController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/SelectiveOptionService.java
BE/feat/exterior_color_feedback -> dev
외장 색상 옵션의 경우, 동적으로 피드백 멘트가 수정되는 하는 로직을 추가하였습니다.
Close #92
> [BE] 외장 색상 옵션 동적 피드백 멘트 수정

- Frontend/index.html
- Frontend/src/components/common/modal/Modal/Modal.style.tsx
- Frontend/src/components/common/modal/Modal/Modal.tsx
- Frontend/src/components/common/modal/ModalPortal.tsx
- 기능 추가
ex) FE/feature/#113 -> fe-dev
일반 모달 창 기능 구현
> [FE] 일반 모달 창 기능 구현

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/SelectiveOptionController.java
BE/fix/selective_option_path -> dev
/selective_option/ 엔드포인트에 오타가 있어 수정했습니다 🥲
> [BE] /selective_option/ 엔드포인트 오타 수정

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/RecommendController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/PurchaseCountDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/RecommendDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/selectiveOptionDto/PackageComponentDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/selectiveOptionDto/RequiredOptionDto.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/PurchaseHistoryRepository.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/PurchaseHistoryRepositoryImpl.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/SelectiveOptionRepository.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/SelectiveOptionRepositoryImpl.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/SelectiveOptionService.java
BE/feat/recommend -> dev
1. /selective_option/ 엔드포인트와 /tag/ 엔드포인트의 통합을 위해 미리 DTO를 일부 수정하였습니다. 해당 수정내용에 맞춰 로직을 수정하면 될 것으로 보입니다.
2. 주어진 카테고리별 로직에 따라 /recommend 엔드포인트를 구현하였습니다.
3. repository 레벨에서 메서드형의 혼란을 피하기 위해 RequiredOption과 OptionPackage의 테이블명을 Category라는 이름으로 수정하여 메서드들을 정의하고 구현하였습니다. 추후 통합 작업이 필요할 것으로 보입니다.
> [BE] /recommend 엔드포인트 구현

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/SelectiveOptionRepositoryImpl.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/SelectiveOptionService.java
BE/fix/recommend-package-empty
POST 요청으로 받아오는 추천옵션ID가 없을 경우 추천패키지는 빈 리스트로 처리합니다.
close #157
> [BE] 가이드모드 추천 패키지 없을시 발생하는 오류 해결

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/controller/SelectiveOptionController.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/domain/DefaultOption.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/dto/DefaultOptionDetailDto.java
BE/feature/add-description-defaultoption
기본포함품목에 설명 필드를 추가합니다.
* 데이터베이스에 description 필드 추가 및 데이터 반영
* DefaultOption 클래스에 description 필드 추가
* DefaultOptionDetailDto 클래스에 description 필드 추가
close #153
> [BE] 기본포함품목에 설명을 추가합니다.

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/SelectiveOptionService.java
BE/feature/sort-recommend-package
추천되는 부가 옵션들에 대해 유사유저 비율 내림차순으로 정렬합니다.
close #160
> [BE] 추천 부가옵션 유사유저 비율로 정렬

- Frontend/src/components/main/LandingMainDetail/MainDetailLayout/DefaultOption/DefaultOption.style.tsx
- Frontend/src/components/main/LandingMainDetail/MainDetailLayout/DefaultOption/Item/Item.style.tsx
- Frontend/src/components/self-mode/OptionItem/OptionImage/OptionImage.style.tsx
- Frontend/src/components/self-mode/OptionItem/OptionImage/OptionImage.tsx
- Frontend/src/components/self-mode/OptionItem/OptionItem.tsx
- Frontend/src/utils/HighlightWord.tsx
- 버그 수정
FE/feature/#163 -> fe-dev
- softeerbootcamp-2nd/A3-OhMyCarSet#163
- 백카사전 이벤트 전파 막기
- 메인 기본 포함 품목 레이아웃 깨짐 수정
- 옵션 컴포넌트 백그라운드 이미지에서 이미지로 변경
- 줄바꿈 추가
> [FE] 백카사전, 메인 페이지 버그 수정

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/CacheUpdateConfig.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/CacheUpdateScheduleConfig.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/PurchaseHistoryRepository.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/repository/PurchaseHistoryRepositoryImpl.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/SelectiveOptionService.java
BE/feat/nogender_recommend -> dev
성별이 '선택 안함'일 때의 프리셋 추천 로직을 수정하였습니다. 해당 경우, 성별과 관련된 로직에서 성별 조건이 무효화됩니다.
#172
> [BE] 성별이 '선택 안함'일 때 /recommend 로직 수정

- Frontend/src/components/guide-mode/GuideComplete/GuideComplete.tsx
- 버그 수정
FE/feature/#189 -> fe-dev
- softeerbootcamp-2nd/A3-OhMyCarSet#189
- 첫 옵션 캐싱 시점 수정했습니다
> [FE] 첫 옵션 캐싱 수정

- Frontend/src/components/complete/Detail/DetailMultiItem/DetailMultiItem.tsx
-  버그 수정
FE/feature/#178 -> fe-dev
견적뽑기페이지에서 일부 필터 선택시 데이터가 안나오던 오류 수정
> [FE]: 견적뽑기완료 페이지 기본 옵션 오류 수정

- Frontend/src/components/modal/DescriptionModal/DescriptionModal.tsx
- 기능 추가
FE/feature/#193 -> fe-dev
기본 포함 품목 모달 고화질 이미지 적용
> [FE] 기본 포함 품목 모달 고화질 이미지 적용

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/service/SelectiveOptionService.java
BE/feature/guidemode-exteriorcolor-feedback -> dev
가이드모드 상세옵션 페이지 외장색상 카테고리에서 구매비율에 따라 동적피드백을 생성하도록 구현했습니다.
1. 모든 외장색상별로 구매비율 순으로 정렬
2. 정렬된 결과에 피드백 추가 (1, 2~3, 4~6)
3. 추천 색상에 대하여 구매비율 -> 유사유저비율로 변경 및 태그 추가
4. 추천색상 / 나머지색상 정렬 후 나머지색상은 구매비율로 재정렬
close #185
> [BE] 가이드모드 외장색상 동적피드백 생성

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/CacheUpdateScheduleConfig.java
- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/RedisConfig.java
BE/fix/test_redis -> dev
1. Redis TTL 및 동기화 주기를 각각 48시간, 24시간으로 변경하였습니다.
2. 이제 CICD 작업에서 테스트 역시 진행하도록 수정하였는데, 스케줄링된 작업(Redis 캐시 동기화 작업)이 Spring 시작과 동시에 작업되는 경우 때때로 Redis 키가 생성되었지만 값이 비어 있어 테스트가 실패하는 경우가 존재하였습니다. 이를 스케줄링 작업들에 최초 Delay를 줘서 해결하였습니다.
> [BE] 테스트를 위해 Redis 설정 일부 수정(최초 스케줄링 대기시간 추가)

- backend/ohmycarset/src/main/java/com/softeer2nd/ohmycarset/config/CacheUpdateScheduleConfig.java
BE/feat/cache_cron -> dev
cron을 이용하여 매일 오전 3시에 Cache Warming이 작동하도록 수정하였습니다.
Close #214
> [BE] 매일 오전 3시에 Cache Warming 작업 진행되도록 cron 작업으로 변경

- README.md
COMMON/feat/readme_infrastructure
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
> [COMMON] 인프라 이미지 추가

- Frontend/src/components/header/CarModelButton/CarModelButton.tsx
- Frontend/src/components/loading/Loading.tsx
- 단어 수정
FE/hotFix -> dev
팰리세이드 단어 변경했습니다
받아주세요 마지막 머지 .. 🥹
> [FE] 팰리세이드 단어 수정
